### ISSUE TITLE
Description for Installing this Script 

### ISSUE THREAD

**Issue by Araibona** [JeremieSiller/kleinanzeigen_bot#1]
Hello, I Would like to install this script on my raspberry pi and run it 24/7 is it possible for you to write a detailed description on how to install it and put more than 1 URL from eBay Kleinanzeigen. Thanks a lot !

**Comment by jerem1e** [comment]
Hey, sure, if I figure out the issues I am still facing. This project is far from perfect/done :/

**Comment by jerem1e** [comment]
FYI, if you just want notifications on telegram, it's easier to just write a httpx + beautifulsoup scraper. I am not even sure if this can run on a raspberry, as it's not very lightweight. It's using selenium, and there needs to be a browser (chrome) installed on the machine for the script to work.

**Comment by jerem1e** [comment]
@Araibona I added a readme now, so if you want to use it, look into it. Also, it's not using selenium any more and therefore more lightweight.
